### ISSUE TITLE
[bug] Claymores will be tripped before arming in Offline lobbies

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [Odex64/SFR#11]
_tripped is set to true in two different places (idk why?), and the one inside the Draw() method causes this issue.
I removed the one in the Draw() method which seemingly worked just as fine, both for offline and networked lobbies.

**Comment by Odex64** [comment]
You can open a PR with your fix if you want to.

**Comment by Kamilkampfwagen-II** [comment]
I can, but what is the purpose of the `_tripped  = true` assignment in the Draw() method? I didn't encounter any issues after removing it, but I could've missed something.

**Comment by Odex64** [comment]
Honestly, I don't know. Motto73 wrote that code long time ago. If everything works as expected in offline and online then you can submit a PR.
