### ISSUE TITLE
[bug] Unable to update spawn chances for SFR items via Script API

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [Odex64/SFR#9]
`Game.GetWeaponSpawnChances` and `Game.ClearWeaponSpawnChances` methods work as expected, however `Game.UpdateWeaponSpawnChances` method won't mutate the values of SFR items.

**Comment by Odex64** [comment]
This should be [fixed](https://github.com/Odex64/SFR/blob/ad98a1c6128108f9192cb7c5a1553e11067a27d7/SFR/Misc/Tweaks.cs#L53-L64)

**Comment by Kamilkampfwagen-II** [comment]
I confirm it is fixed 👍
